swagger: '2.0'
info:
  description: Interactive Documentation
  version: '2.0'
  title: Ota
  contact:
    name: JeanMary LECOUTEUX
    email: jeanmary@gmail.com
consumes:
- multipart/form-data
- application/x-www-form-urlencoded
produces:
- application/json; version=2.0

schemes:
- http

basePath: /

paths:
  /users:
    get:
      tags:
      - user
      summary: "List all users"
      parameters:

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UsersResponse'
  /users/{id}:
    get:
      tags:
      - user
      summary: "Get info for a single user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'


definitions:
  UsersResponse:
    type: array
    items:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        name:
          type: string
        dob:
          type: date
        age:
          type: integer
        address_line_1:
          type: string

  UserResponse:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      name:
        type: string
      dob:
        type: date
      age:
        type: integer
      address_line_1:
        type: string

  NotFoundResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Not Found'
