swagger: '2.0'
info:
  description: Interactive Documentation
  version: '2.0'
  title: Ota
  contact:
    name: JeanMary LECOUTEUX
    email: jeanmary@gmail.com
consumes:
- multipart/form-data
- application/x-www-form-urlencoded
produces:
- application/json; version=2.0

schemes:
- http

basePath: /

paths:
  /sessions:
    post:
      tags:
      - session
      summary: "Identify the user and get his token"
      parameters:
      - username:
        name: username
        type: string
        in: query
        required: true
      - password:
        name: password
        type: string
        in: query
        required: true

      responses:
        201:
          description: Successful operation
          schema:
            $ref: '#/definitions/TokenResponse'
        401:
          description: Unknown user
          schema:
            $ref: '#/definitions/UnauthorizedResponse'


  /users:
    get:
      tags:
      - user
      summary: "List all users"
      parameters:

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UsersResponse'

    post:
      tags:
      - user
      summary: "Create an user"
      parameters:
      - first_name:
        name: first_name
        in: query
        type: string
        required: true

      - last_name:
        name: last_name
        in: query
        type: string
        required: true

      - dob:
        name: dob
        in: query
        type: string
        format: date
        required: true

      - address_line_1:
        name: address_line_1
        in: query
        type: string
        required: true

      responses:
        201:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

  /users/{id}:
    get:
      tags:
      - user
      summary: "Get info for a single user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

    patch:
      tags:
      - user
      summary: "Update an user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer

      - first_name:
        name: first_name
        in: query
        type: string

      - last_name:
        name: last_name
        in: query
        type: string

      - dob:
        name: dob
        in: query
        type: string
        format: date

      - address_line_1:
        name: address_line_1
        in: query
        type: string

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - user
      summary: "Destroy a single user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Successful operation
          schema:
            $ref: '#/definitions/DeletedResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

  /users/{user_id}/transfers:
    get:
      tags:
      - transfer
      summary: "List user's transfers"
      parameters:
      - name: user_id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/TransfersResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

    post:
      tags:
      - transfer
      summary: "Create a transfer for this user"
      parameters:
      - name: user_id
        in: path
        required: true
        type: integer

      - account_number_from:
        name: account_number_from
        in: query
        type: string
        required: true

      - account_number_to:
        name: account_number_to
        in: query
        type: string
        required: true

      - country_code_from:
        name: country_code_from
        in: query
        type: string
        required: true

      - country_code_to:
        name: country_code_to
        in: query
        type: string
        required: true

      - amount_pennies:
        name: amount_pennies
        in: query
        type: number
        format: float
        required: true

      responses:
        201:
          description: Successful operation
          schema:
            $ref: '#/definitions/TransferResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

  /users/{user_id}/transfers/{id}:
    get:
      tags:
      - transfer
      summary: "List user's transfers"
      parameters:
      - name: user_id
        in: path
        required: true
        type: integer
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/TransferResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

    patch:
      tags:
      - transfer
      summary: "Update an user's transfer"
      parameters:
      - name: id
        in: path
        required: true
        type: integer

      - name: user_id
        in: path
        required: true
        type: integer

      - account_number_from:
        name: account_number_from
        in: query
        type: string

      - account_number_to:
        name: account_number_to
        in: query
        type: string

      - country_code_from:
        name: country_code_from
        in: query
        type: string

      - country_code_to:
        name: country_code_to
        in: query
        type: string

      - amount_pennies:
        name: amount_pennies
        in: query
        type: number
        format: float

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/TransferResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - transfer
      summary: "Destroy an user's transfer"
      parameters:
      - name: user_id
        in: path
        required: true
        type: integer
      - name: id
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Successful operation
          schema:
            $ref: '#/definitions/DeletedResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

definitions:
  TokenResponse:
    type: object
    properties:
      auth_token:
        type: string

  UsersResponse:
    type: array
    items:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        name:
          type: string
        dob:
          type: string
          format: date
        age:
          type: integer
        address_line_1:
          type: string

  UserResponse:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      name:
        type: string
      dob:
        type: string
        format: date
      age:
        type: integer
      address_line_1:
        type: string

  TransfersResponse:
    type: array
    items:
      type: object
      properties:
        account_number_from:
          type: string
        account_number_to:
          type: string
        country_code_from:
          type: string
        country_code_to:
          type: string
        amount_pennies:
          type: number
          format: float

  TransferResponse:
    type: object
    properties:
      account_number_from:
        type: string
      account_number_to:
        type: string
      country_code_from:
        type: string
      country_code_to:
        type: string
      amount_pennies:
        type: number
        format: float

  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string

  NotFoundResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Not Found'

  DeletedResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Deleted'

  UnauthorizedResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Unauthorized'
