swagger: '2.0'
info:
  description: Interactive Documentation
  version: '2.0'
  title: Ota
  contact:
    name: JeanMary LECOUTEUX
    email: jeanmary@gmail.com
consumes:
- multipart/form-data
- application/x-www-form-urlencoded
produces:
- application/json; version=2.0

schemes:
- http

basePath: /

paths:
  /users:
    get:
      tags:
      - user
      summary: "List all users"
      parameters:

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UsersResponse'

    post:
      tags:
      - user
      summary: "Create an user"
      parameters:
      - first_name:
        name: first_name
        in: query
        type: string
        required: true

      - last_name:
        name: last_name
        in: query
        type: string
        required: true

      - dob:
        name: dob
        in: query
        type: string
        format: date
        required: true

      - address_line_1:
        name: address_line_1
        in: query
        type: string
        required: true

      responses:
        201:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

  /users/{id}:
    get:
      tags:
      - user
      summary: "Get info for a single user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'

    patch:
      tags:
      - user
      summary: "Update an user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer

      - first_name:
        name: first_name
        in: query
        type: string

      - last_name:
        name: last_name
        in: query
        type: string

      - dob:
        name: dob
        in: query
        type: string
        format: date

      - address_line_1:
        name: address_line_1
        in: query
        type: string

      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/UserResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'

    delete:
      tags:
      - user
      summary: "Destroy a single user"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        204:
          description: Successful operation
          schema:
            $ref: '#/definitions/DeletedResponse'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/NotFoundResponse'


definitions:
  UsersResponse:
    type: array
    items:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        name:
          type: string
        dob:
          type: string
          format: date
        age:
          type: integer
        address_line_1:
          type: string

  UserResponse:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      name:
        type: string
      dob:
        type: string
        format: date
      age:
        type: integer
      address_line_1:
        type: string

  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string

  NotFoundResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Not Found'

  DeletedResponse:
    type: object
    properties:
      message:
        type: string
        example: 'Deleted'
